# Generated by Django 2.1.2 on 2019-05-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190504_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단위'),
        ),
        migrations.AddField(
            model_name='stock',
            name='s_count',
            field=models.IntegerField(default=0, verbose_name='재고량'),
        ),
        migrations.AddField(
            model_name='stock',
            name='s_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='단위'),
        ),
    ]
