# Generated by Django 2.1.2 on 2019-05-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190504_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_log', models.CharField(max_length=100, verbose_name='변경사항')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='o_count',
            field=models.PositiveIntegerField(verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='order',
            name='o_name',
            field=models.CharField(max_length=30, verbose_name='품명'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_caution_num',
            field=models.PositiveIntegerField(verbose_name='경고 수량'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_name',
            field=models.CharField(max_length=30, verbose_name='재고명'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='sl_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.Stock', verbose_name='재고명'),
        ),
    ]
