# Generated by Django 2.1.2 on 2019-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190506_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='s_caution_num',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='경고 수량'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='유통기한'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_incoming_at',
            field=models.DateField(blank=True, null=True, verbose_name='반입일자'),
        ),
    ]
