# Generated by Django 2.1.2 on 2019-05-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20190506_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklog',
            name='sl_name',
        ),
        migrations.DeleteModel(
            name='Stocklog',
        ),
    ]
