# Generated by Django 2.2 on 2019-05-07 12:03

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='m_pic',
            field=models.ImageField(blank=True, null=True, upload_to=Main.models.directory_url, verbose_name='사진'),
        ),
    ]
