# Generated by Django 2.2 on 2019-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20190507_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='sl_created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='로그 시간'),
        ),
    ]
