# Generated by Django 2.2 on 2019-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_stocklog_sl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='o_count',
            field=models.FloatField(verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='s_count',
            field=models.FloatField(default=0, verbose_name='재고량'),
        ),
    ]
