# Generated by Django 2.2 on 2019-05-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20190507_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_order_date', models.DateTimeField(auto_now=True, verbose_name='주문 시간')),
                ('to_count', models.PositiveIntegerField(verbose_name='개수')),
                ('to_status', models.CharField(max_length=10, verbose_name='주문 상태')),
                ('to_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Menu', verbose_name='메뉴')),
            ],
        ),
        migrations.CreateModel(
            name='Order_sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_table_no', models.PositiveIntegerField(verbose_name='테이블 번호')),
                ('os_amount', models.PositiveIntegerField(verbose_name='총액')),
                ('os_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Table_order', verbose_name='주문서')),
            ],
        ),
    ]
