# Generated by Django 2.2 on 2019-05-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20190521_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_sheet',
            name='os_menu',
        ),
        migrations.AddField(
            model_name='table_order',
            name='to_order_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Order_sheet', verbose_name='주문서'),
        ),
    ]
