# Generated by Django 2.2 on 2019-05-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_auto_20190521_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_profit_date', models.DateTimeField(auto_now_add=True)),
                ('p_detail', models.CharField(max_length=100)),
                ('p_amount', models.IntegerField(default=0)),
                ('p_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Table_order')),
            ],
        ),
    ]
