# Generated by Django 2.2 on 2019-05-21 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='p_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Order_sheet'),
        ),
    ]
