# Generated by Django 2.2 on 2019-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0019_auto_20190521_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_sheet',
            name='os_status',
            field=models.BooleanField(default=True, verbose_name='활성여부'),
        ),
    ]
