# Generated by Django 2.2.1 on 2019-05-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_order_sheet_os_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='교육명')),
                ('education_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='교육내용 또는 소개')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='직원명')),
                ('employee_pic', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='종업원사진')),
                ('sex', models.CharField(blank=True, max_length=10, null=True, verbose_name='성별')),
                ('employee_phone', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='핸드폰')),
                ('employee_email', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='이메일')),
                ('resident_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='주민등록번호')),
                ('employee_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('employee_bank', models.CharField(blank=True, max_length=20, null=True, verbose_name='은행명')),
                ('employee_banknumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='계좌번호')),
                ('employee_isdelete', models.BooleanField(default=False, verbose_name='삭제')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='사명')),
                ('license_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='사업자번호')),
                ('business', models.CharField(blank=True, max_length=50, null=True, verbose_name='업종')),
                ('restaurant_pic', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='식당사진')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='등록일')),
                ('restaurant_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('user_id', models.CharField(default='', max_length=30, verbose_name='ID')),
                ('user_pw', models.CharField(default='', max_length=30, verbose_name='PW')),
                ('phone', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='핸드폰')),
                ('e_mail', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='이메일')),
                ('user_pic', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='사진')),
                ('user_bank', models.CharField(blank=True, max_length=20, null=True, verbose_name='은행명')),
                ('user_banknumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='계좌번호')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명')),
            ],
        ),
        migrations.CreateModel(
            name='Iseducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscomplete', models.BooleanField(default=False, verbose_name='이수')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Education', verbose_name='교육명')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Employee', verbose_name='사원명')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명'),
        ),
        migrations.AddField(
            model_name='education',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명'),
        ),
    ]
