# Generated by Django 2.2 on 2019-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_order_sheet_os_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_spending_date', models.DateTimeField(auto_now_add=True)),
                ('s_detail', models.CharField(default='', max_length=100)),
                ('s_expense', models.IntegerField(default=0)),
            ],
        ),
    ]
