# Generated by Django 2.2.1 on 2019-05-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_auto_20190525_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='교육사진'),
        ),
    ]
