# Generated by Django 2.2 on 2019-05-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_spending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '메뉴', 'verbose_name_plural': '메뉴'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '발주', 'verbose_name_plural': '발주'},
        ),
        migrations.AlterModelOptions(
            name='order_sheet',
            options={'verbose_name': '주문서', 'verbose_name_plural': '주문서'},
        ),
        migrations.AlterModelOptions(
            name='profit',
            options={'verbose_name': '수익', 'verbose_name_plural': '수익'},
        ),
        migrations.AlterModelOptions(
            name='spending',
            options={'verbose_name': '지출', 'verbose_name_plural': '지출'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '재고', 'verbose_name_plural': '재고'},
        ),
        migrations.AlterModelOptions(
            name='stocklog',
            options={'verbose_name': '재고 기록', 'verbose_name_plural': '재고 기록'},
        ),
        migrations.AlterModelOptions(
            name='table_order',
            options={'verbose_name': '주문 메뉴', 'verbose_name_plural': '주문 메뉴'},
        ),
    ]
