# Generated by Django 2.2 on 2019-05-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_auto_20190522_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_note',
            field=models.CharField(max_length=50, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='order',
            name='o_target',
            field=models.CharField(max_length=30, null=True, verbose_name='거래처'),
        ),
    ]
