# Generated by Django 2.2.1 on 2019-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_education_education_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_isdelete',
            field=models.BooleanField(default=False, verbose_name='삭제'),
        ),
    ]
