# Generated by Django 2.2.1 on 2019-05-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_education_education_isdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime_work', models.IntegerField(default=0, verbose_name='주간근무')),
                ('night_work', models.IntegerField(default=0, verbose_name='야간근무')),
                ('day_work', models.DateTimeField(auto_now_add=True, verbose_name='근무일')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Employee', verbose_name='사원명')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_pay', models.IntegerField(default=0, verbose_name='급여')),
                ('day_pay', models.DateTimeField(auto_now_add=True, verbose_name='지급일')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Employee', verbose_name='사원명')),
            ],
        ),
    ]
