# Generated by Django 2.2 on 2019-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_auto_20190523_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='sl_category',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
