# Generated by Django 2.2.1 on 2019-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_pay_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='day_work',
        ),
        migrations.AddField(
            model_name='work',
            name='end_day_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='근무종료'),
        ),
        migrations.AddField(
            model_name='work',
            name='start_day_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='근무시작'),
        ),
        migrations.AddField(
            model_name='work',
            name='total_work',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='총근무'),
        ),
        migrations.AlterField(
            model_name='work',
            name='daytime_work',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='주간근무'),
        ),
        migrations.AlterField(
            model_name='work',
            name='night_work',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='야간근무'),
        ),
    ]
