# Generated by Django 2.2 on 2019-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0024_stocklog_sl_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_order',
            name='to_isActive',
            field=models.BooleanField(default=True),
        ),
    ]
