# Generated by Django 2.2 on 2019-05-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0025_table_order_to_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='p_os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Order_sheet'),
        ),
    ]
