# Generated by Django 2.2.1 on 2019-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0027_employee_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='daytime_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='주간근무'),
        ),
        migrations.AlterField(
            model_name='work',
            name='night_work',
            field=models.IntegerField(blank=True, null=True, verbose_name='야간근무'),
        ),
    ]
