# Generated by Django 2.2.1 on 2019-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0029_auto_20190526_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='근무파트'),
        ),
    ]
