# Generated by Django 2.2.1 on 2019-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0030_work_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_isdelete',
            field=models.BooleanField(default=False, verbose_name='삭제'),
        ),
    ]
