# Generated by Django 2.2.1 on 2019-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0031_work_work_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='day_work',
            field=models.DateField(blank=True, null=True, verbose_name='근무일'),
        ),
    ]
