# Generated by Django 2.2.1 on 2019-05-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0032_auto_20190526_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='all_pay',
        ),
        migrations.AddField(
            model_name='pay',
            name='other_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='특별수당'),
        ),
        migrations.AddField(
            model_name='pay',
            name='whole_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='총수당'),
        ),
        migrations.AddField(
            model_name='pay',
            name='work_pay',
            field=models.IntegerField(blank=True, null=True, verbose_name='정기수당'),
        ),
    ]
