# Generated by Django 2.2.1 on 2019-05-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0034_pay_pay_isdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='iseducation',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명'),
        ),
        migrations.AddField(
            model_name='pay',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명'),
        ),
        migrations.AddField(
            model_name='work',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명'),
        ),
    ]
