# Generated by Django 2.2.1 on 2019-05-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0035_auto_20190526_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='이름')),
                ('apply_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='핸드폰')),
                ('apply_email', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='이메일')),
                ('apply_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('apply_academic', models.CharField(blank=True, max_length=20, null=True, verbose_name='최종학력')),
                ('apply_career', models.TextField(blank=True, max_length=300, null=True, verbose_name='경력')),
                ('apply_motive', models.TextField(blank=True, max_length=300, null=True, verbose_name='지원동기')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명')),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_title', models.CharField(blank=True, default='없음', max_length=50, null=True, verbose_name='제목')),
                ('hire_content', models.TextField(blank=True, default='없음', max_length=400, null=True, verbose_name='내용')),
                ('hire_pic', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='등록사진')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Restaurant', verbose_name='소속명')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.User', verbose_name='등록자명')),
            ],
        ),
    ]
