# Generated by Django 2.2.1 on 2019-05-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0036_hire_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='hire_pic',
        ),
    ]
