# Generated by Django 2.2 on 2019-05-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0026_auto_20190524_2307'),
        ('Main', '0037_remove_hire_hire_pic'),
    ]

    operations = [
    ]
