# Generated by Django 2.2 on 2019-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0038_merge_20190527_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_expense',
            field=models.IntegerField(default=0, verbose_name='비용'),
        ),
    ]
