# Generated by Django 2.2 on 2019-05-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0039_order_o_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='s_primary_key',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
