# Generated by Django 2.2 on 2019-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0040_spending_s_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_isAcitve',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
    ]
